---
title: "HiSeq Plot"
author: "Ming Wang"
runtime: shiny
output: html_document
---


```{r setup, include=FALSE}
suppressPackageStartupMessages(library(knitr))

knitr::opts_chunk$set(fig.width  = 12, 
                      fig.height = 8, 
                      fig.path   = "Figures/",
                      eval       = TRUE,
                      echo       = FALSE,
                      cache      = FALSE,
                      prompt     = FALSE,
                      tidy       = FALSE,
                      comment    = NA,
                      message    = FALSE,
                      warning    = FALSE,
                      rownames.print = FALSE)
```



# 1. To-do list

-[]  scatter  
-[]  heatmap  
-[]  volcano  
-[]  venn-diagram  

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item



# 2. 维恩图

参考 [venn](https://bioinfogp.cnb.csic.es/tools/venny/index.html) 和 [ggvenn](https://github.com/yanlinlin82/ggvenn)

+ 支持2-4个list   
+ 上方输入 名称， 下方输入 具体列表，例如基因名称    
+ **透明度** 调整为0，可以去除颜色    

```{r}
library(shiny)
library(dplyr)
library(ggvenn)

## helper functions
read_textbox <- function(x) {
  if(inherits(x, "character")) {
    x_items <- stringr::str_split(x, ",| |\\\t|\\\n", simplify = TRUE)
    x_items <- as.vector(x_items)
    # remove blanks
    x_items <- x_items[! x_items == ""]
    
  } else {
    x_items <- c()
  }
  return(x_items)
}


## server
get_vennplot <- function() {
  renderPlot({
    # read from box
    a <- list(A = read_textbox(input$boxA),
              B = read_textbox(input$boxB),
              C = read_textbox(input$boxC),
              D = read_textbox(input$boxD))
    
    # remove empty
    chk <- sapply(a, function(i){length(i) > 0})
    a   <- a[chk]
    
    # read from name
    b <- c(input$nameA, input$nameB, input$nameC, input$nameD)
    names(a) <- b[chk]
    
    # for blank
    if(length(a) == 0) {
      a <- list(A = c(), B = c())
    } else if (length(a) == 1) {
      a <- list(A = a[[1]],
                B = c())
    } else {
      x = 1
    }
    
    # create plot
    ggvenn(a, show_percentage = FALSE,
           fill_alpha = input$fill_alpha,
           stroke_size = input$stroke_size,
           text_size = input$text_size)
  })
}


##-UI---------------
sidebarLayout(
  sidebarPanel(
    fluidRow(
      column(6,
             textInput("nameA", "List 1", 
                       value = "A"),
             textAreaInput("boxA", NULL,
                           value = NULL,
                           rows = 6,
                           placeholder = "输入序列",
                           resize = "vertical" )),
      column(6,
             textInput("nameB", "List 2", 
                       value = "B"),
             textAreaInput("boxB", NULL,
                           value = NULL,
                           rows = 6,
                           placeholder = "输入序列",
                           resize = "vertical"))
    ),
    
    fluidRow(
      column(6, 
             textInput("nameC", "List 3", 
                       value = "C"),
             textAreaInput("boxC", NULL,
                           value = NULL,
                           rows = 6,
                           placeholder = "输入序列",
                           resize = "vertical")),
      column(6,
             textInput("nameD", "List 4", 
                       value = "D"),
             textAreaInput("boxD", NULL,
                           value = NULL,
                           rows = 6,
                           placeholder = "输入序列",
                           resize = "vertical"))
    ),
  ),
  
  mainPanel(
    fluidRow(
      column(4,
             sliderInput("text_size", "字体大小",
                         min = 1, max = 20, value = 4)),
      column(4,
             sliderInput("stroke_size", "线条粗细",
                         min = 0.1, max = 3, value = 1)),
      column(4, 
             sliderInput("fill_alpha", "透明度",
                         min = 0, max = 1, value = 0.5))
    ),
    
    fluidRow(
      get_vennplot()
    )
  )
)

```


# 3. 火山图




### Results

list of tables





























**END**
